### ISSUE TITLE
Fixing the fact I cant even get on server. 

### ISSUE THREAD

**Issue by hbricky** [Calemi/CalemiUtils-1.16.4#10]
Hello, i have a server i personally run off my computer and not a third party and i was trying to /give myself some dollars from the mod and i tend to type fast so i overytyped and gave myself so much thats enough to crash the whole server. I cant even get on neither me or anyone and it crashes and ive tried putting commands but it doesnt work because it just keeps crashing. I dont want to find a different currency mod since ive had this mod the longest and its by far my favorite one. Its an honest mistake and i need help on what to do so i can keep the mod and play on my server again. 

Thanks, and someone please help.

**Comment by Calemi** [comment]
Hmmm... That's quite an issue to have. There are not many ways I can think of that could fix it.

You could try removing the mod. Without the mod, the items would probably disappear and you'd be able to safely log in. Then just place the mod back in afterward. HOWEVER, if you have stuff from the mod (like blocks or items) in that world, they would get removed as well.

Other than that, I'm not sure if any third-party apps like MCEDIT or something like that are updated, but if one is, I would try that too.

For the future, I highly recommend you download FTBBackups or any other auto-backup addon, so you can easily revert to an earlier save file.
