### ISSUE TITLE
Missing gradle project files

### ISSUE THREAD

**Issue by alfiejfs** [Calemi/CalemiUtils-1.16.4#12]
I tried to fork this project, only to realise that the gradle.properties and gradle wrapper are missing. This proved extremely unhelpful when trying to do anything with the mod.

Can you push these? Much appreciated

Asking specifically for:

 - gradle/wrapper
 - gradlew
 - gradlew.bat
 - gradle.properties
 - settings.gradle

EDIT: Perhaps I'm just a gradle noob, upon further research it seems it is possible to build if I scrape together versionings and run some forge gradle commands? But seems more convenient to have these on the project anyway.

**Comment by Calemi** [comment]
Sorry for the extremely late reply. Been real busy with life. I know its probably way too late, but I'm pushing those files
