### ISSUE TITLE
Break Bookstand Crash

### ISSUE THREAD

**Issue by Hurricaneforces** [Calemi/CalemiUtils-1.16.4#13]
Break the Bookstand with Linked Book  immediately Crash my game

Version 1.1.1
Enigmatica 6 Pack
[crash-2021-04-27_15.21.57-client.txt](https://github.com/Calemi/CalemiUtils-1.16.4/files/6383082/crash-2021-04-27_15.21.57-client.txt)

**Comment by MadHattress** [comment]
I am also having this issue! Does the creator read these and fix them? I really love this mod and this isn't a huge issue but it crashed our multiplayer server and everyone had to restart their mc launcher to get back in.

**Comment by Calemi** [comment]
Sorry about the very late reply. Been busy with life. This issue should be fixed in the next build.
