### ISSUE TITLE
/cutils command just... gone?

### ISSUE THREAD

**Issue by ViridianFire** [Calemi/CalemiUtils-1.16.4#18]
It just doesn't exist
![image](https://user-images.githubusercontent.com/84670775/127673848-3ce75f73-7ec4-4911-83c6-5e1e2061d47f.png)
Calemi's Utils Version 1.16.5-1.1.3

**Comment by Calemi** [comment]
Huh, that's weird... I'll check it out when I get a chance.

**Comment by Calemi** [comment]
So I did some testing and I couldn't replicate the bug on singleplayer or multiplayer. It must be another mod interfering with it. Could I get a list of the mods you are playing with?
