### ISSUE TITLE
[Feature Request] Explosion Resistance 

### ISSUE THREAD

**Issue by kreezxil** [Calemi/CalemiUtils-1.16.4#19]
Although we noticed that blocks placed with the shop can only be directly destroyed by the player that placed them, we did discover that TNT will destroy them out right.

These shops need either resistance to all types of explosions, or you could add another utility that stops explosions in an area.

**Comment by Calemi** [comment]
This was definitely an oversight on my part. I'll make all secured blocks completely blast-resistant in the next build. Thanks!
