### ISSUE TITLE
[Suggestion] Add a Crafting recipe for all of the coins.

### ISSUE THREAD

**Issue by AC3SSoccerball** [Calemi/CalemiUtils-1.16.4#24]
Hi, I was wondering if you would be able to make crafting recipes for all of the coins, it's really annoying having my players have to go into the mines to collect coins.
Thanks :)

**Comment by Calemi** [comment]
I probably won't end up making this an optional thing unfortunately. It doesn't fit with my idea/plan for the currency. Although you can set up some crafting recipes with CraftTweaker
