### ISSUE TITLE
Limit in Server Side Market?

### ISSUE THREAD

**Issue by Beastbrown111** [Calemi/CalemiUtils-1.16.4#4]
I was entering trades in the buy sell files in the config and once I hit 50 items it cant add anymore. If I add anymore than 50 it will load into the game but when I go to click the Market the game freezes and crashes to launcher. Here is the crash report. If the max is truly 50 is there anyway to change this or will this be increased in the future? I ask because this is a great server side market mechanic. Thanks 

[crash-2021-01-10_20.43.51-client.txt](https://github.com/Calemi/CalemiUtils-1.16.4/files/5793809/crash-2021-01-10_20.43.51-client.txt)

**Comment by VeganGod** [comment]
PLEASE fix this, I have 81 things I need to put in the market :(
